groups:
  - name: slam-poker-system-health
    interval: 30s
    rules:
      - alert: SystemHealthCritical
        expr: '{service="slam-poker"} |= "health_score" | json | health_score != "" | unwrap health_score < 60'
        for: 2m
        labels:
          severity: critical
          category: system-health
          service: slam-poker
        annotations:
          summary: "SLAM Poker system health is critically low"
          description: "System health score is {{ $value }}%, which is below the critical threshold of 60%"
          runbook_url: "https://docs.example.com/runbooks/system-health-critical"

      - alert: SystemHealthWarning
        expr: '{service="slam-poker"} |= "health_score" | json | health_score != "" | unwrap health_score < 80'
        for: 5m
        labels:
          severity: warning
          category: system-health
          service: slam-poker
        annotations:
          summary: "SLAM Poker system health is degraded"
          description: "System health score is {{ $value }}%, which is below the warning threshold of 80%"
          runbook_url: "https://docs.example.com/runbooks/system-health-warning"

      - alert: HighErrorRate
        expr: 'rate({service="slam-poker"} |= "error_category" [5m]) > 0.1'
        for: 2m
        labels:
          severity: critical
          category: errors
          service: slam-poker
        annotations:
          summary: "High error rate detected in SLAM Poker"
          description: "Error rate is {{ $value }} errors per second, exceeding critical threshold of 0.1/sec"
          runbook_url: "https://docs.example.com/runbooks/high-error-rate"

      - alert: MemoryUsageHigh
        expr: '{service="slam-poker"} |= "memory_usage_mb" | json | memory_usage_mb != "" | unwrap memory_usage_mb > 1024'
        for: 5m
        labels:
          severity: warning
          category: resource-usage
          service: slam-poker
        annotations:
          summary: "High memory usage in SLAM Poker"
          description: "Memory usage is {{ $value }}MB, exceeding warning threshold of 1024MB"
          runbook_url: "https://docs.example.com/runbooks/high-memory-usage"

      - alert: MemoryUsageCritical
        expr: '{service="slam-poker"} |= "memory_usage_mb" | json | memory_usage_mb != "" | unwrap memory_usage_mb > 2048'
        for: 2m
        labels:
          severity: critical
          category: resource-usage
          service: slam-poker
        annotations:
          summary: "Critical memory usage in SLAM Poker"
          description: "Memory usage is {{ $value }}MB, exceeding critical threshold of 2048MB"
          runbook_url: "https://docs.example.com/runbooks/critical-memory-usage"

  - name: slam-poker-performance
    interval: 30s
    rules:
      - alert: HighResponseTime
        expr: 'quantile_over_time(0.95, {service="slam-poker"} |= "HTTP request completed" | json | duration_ms != "" | unwrap duration_ms [5m]) > 2000'
        for: 3m
        labels:
          severity: warning
          category: performance
          service: slam-poker
        annotations:
          summary: "High HTTP response times in SLAM Poker"
          description: "95th percentile response time is {{ $value }}ms, exceeding threshold of 2000ms"
          runbook_url: "https://docs.example.com/runbooks/high-response-time"

      - alert: CriticalResponseTime
        expr: 'quantile_over_time(0.95, {service="slam-poker"} |= "HTTP request completed" | json | duration_ms != "" | unwrap duration_ms [5m]) > 5000'
        for: 1m
        labels:
          severity: critical
          category: performance
          service: slam-poker
        annotations:
          summary: "Critical HTTP response times in SLAM Poker"
          description: "95th percentile response time is {{ $value }}ms, exceeding critical threshold of 5000ms"
          runbook_url: "https://docs.example.com/runbooks/critical-response-time"

      - alert: WebSocketConnectionIssues
        expr: 'rate({service="slam-poker"} |= "WebSocket connection closed" [5m]) / rate({service="slam-poker"} |= "WebSocket connection established" [5m]) > 0.5'
        for: 2m
        labels:
          severity: warning
          category: connectivity
          service: slam-poker
        annotations:
          summary: "High WebSocket disconnection rate"
          description: "WebSocket disconnection rate is {{ $value }}, exceeding threshold of 0.5"
          runbook_url: "https://docs.example.com/runbooks/websocket-issues"

      - alert: HTTPErrorRateHigh
        expr: 'rate({service="slam-poker"} |= "HTTP request failed" | json | status_code =~ "5[0-9][0-9]" [5m]) > 0.05'
        for: 2m
        labels:
          severity: critical
          category: http-errors
          service: slam-poker
        annotations:
          summary: "High HTTP 5xx error rate"
          description: "HTTP 5xx error rate is {{ $value }}/sec, exceeding threshold of 0.05/sec"
          runbook_url: "https://docs.example.com/runbooks/http-5xx-errors"

  - name: slam-poker-application
    interval: 60s
    rules:
      - alert: RoomCreationFailures
        expr: 'rate({service="slam-poker"} |= "Cannot create room" [10m]) > 0.01'
        for: 5m
        labels:
          severity: warning
          category: application
          service: slam-poker
        annotations:
          summary: "Room creation failures detected"
          description: "Room creation failure rate is {{ $value }}/sec, exceeding threshold of 0.01/sec"
          runbook_url: "https://docs.example.com/runbooks/room-creation-failures"

      - alert: UserEngagementDrop
        expr: '{service="slam-poker"} |= "engagement_rate" | json | engagement_rate != "" | unwrap engagement_rate < 0.3'
        for: 10m
        labels:
          severity: warning
          category: business-metrics
          service: slam-poker
        annotations:
          summary: "User engagement has dropped significantly"
          description: "User engagement rate is {{ $value }}, below threshold of 0.3"
          runbook_url: "https://docs.example.com/runbooks/low-engagement"

      - alert: VotingCompletionRateLow
        expr: '{service="slam-poker"} |= "voting_completion_rate" | json | voting_completion_rate != "" | unwrap voting_completion_rate < 70'
        for: 15m
        labels:
          severity: warning
          category: business-metrics
          service: slam-poker
        annotations:
          summary: "Low voting completion rate"
          description: "Voting completion rate is {{ $value }}%, below threshold of 70%"
          runbook_url: "https://docs.example.com/runbooks/low-voting-completion"

      - alert: SessionDurationTooShort
        expr: '{service="slam-poker"} |= "average_session_duration_minutes" | json | average_session_duration_minutes != "" | unwrap average_session_duration_minutes < 5'
        for: 10m
        labels:
          severity: warning
          category: business-metrics
          service: slam-poker
        annotations:
          summary: "Average session duration is too short"
          description: "Average session duration is {{ $value }} minutes, below threshold of 5 minutes"
          runbook_url: "https://docs.example.com/runbooks/short-sessions"

  - name: slam-poker-errors
    interval: 30s
    rules:
      - alert: ErrorSpikeCritical
        expr: 'sum(increase({service="slam-poker"} |= "High error rate detected" [5m])) > 0'
        for: 0m
        labels:
          severity: critical
          category: error-spike
          service: slam-poker
        annotations:
          summary: "Critical error spike detected"
          description: "Error spike detection system has triggered, indicating abnormal error patterns"
          runbook_url: "https://docs.example.com/runbooks/error-spike"

      - alert: SystemErrorsHigh
        expr: 'rate({service="slam-poker"} |= "system_error" [5m]) > 0.02'
        for: 2m
        labels:
          severity: critical
          category: system-errors
          service: slam-poker
        annotations:
          summary: "High system error rate"
          description: "System error rate is {{ $value }}/sec, exceeding threshold of 0.02/sec"
          runbook_url: "https://docs.example.com/runbooks/system-errors"

      - alert: AuthenticationErrorsHigh
        expr: 'rate({service="slam-poker"} |= "authentication_error" [5m]) > 0.05'
        for: 3m
        labels:
          severity: warning
          category: authentication
          service: slam-poker
        annotations:
          summary: "High authentication error rate"
          description: "Authentication error rate is {{ $value }}/sec, exceeding threshold of 0.05/sec"
          runbook_url: "https://docs.example.com/runbooks/auth-errors"

      - alert: ValidationErrorsHigh
        expr: 'rate({service="slam-poker"} |= "validation_error" [5m]) > 0.1'
        for: 5m
        labels:
          severity: warning
          category: validation
          service: slam-poker
        annotations:
          summary: "High validation error rate"
          description: "Validation error rate is {{ $value }}/sec, exceeding threshold of 0.1/sec"
          runbook_url: "https://docs.example.com/runbooks/validation-errors"

  - name: slam-poker-capacity
    interval: 60s
    rules:
      - alert: HighConcurrentUsers
        expr: '{service="slam-poker"} |= "total_active_users" | json | total_active_users != "" | unwrap total_active_users > 500'
        for: 5m
        labels:
          severity: warning
          category: capacity
          service: slam-poker
        annotations:
          summary: "High number of concurrent users"
          description: "{{ $value }} concurrent users, approaching capacity limit of 500"
          runbook_url: "https://docs.example.com/runbooks/high-user-count"

      - alert: CriticalConcurrentUsers
        expr: '{service="slam-poker"} |= "total_active_users" | json | total_active_users != "" | unwrap total_active_users > 800'
        for: 2m
        labels:
          severity: critical
          category: capacity
          service: slam-poker
        annotations:
          summary: "Critical number of concurrent users"
          description: "{{ $value }} concurrent users, exceeding safe capacity of 800"
          runbook_url: "https://docs.example.com/runbooks/critical-user-count"

      - alert: HighRoomCount
        expr: '{service="slam-poker"} |= "total_rooms" | json | total_rooms != "" | unwrap total_rooms > 100'
        for: 5m
        labels:
          severity: warning
          category: capacity
          service: slam-poker
        annotations:
          summary: "High number of active rooms"
          description: "{{ $value }} active rooms, approaching capacity considerations"
          runbook_url: "https://docs.example.com/runbooks/high-room-count"

  - name: slam-poker-availability
    interval: 60s
    rules:
      - alert: ServiceDown
        expr: 'absent_over_time({service="slam-poker"} |= "SLAM Poker server initialized" [5m])'
        for: 1m
        labels:
          severity: critical
          category: availability
          service: slam-poker
        annotations:
          summary: "SLAM Poker service appears to be down"
          description: "No server initialization logs detected in the last 5 minutes"
          runbook_url: "https://docs.example.com/runbooks/service-down"

      - alert: HealthCheckFailing
        expr: 'absent_over_time({service="slam-poker"} |= "Health check endpoint accessed" [3m])'
        for: 2m
        labels:
          severity: critical
          category: availability
          service: slam-poker
        annotations:
          summary: "Health check endpoint not responding"
          description: "No health check logs detected in the last 3 minutes"
          runbook_url: "https://docs.example.com/runbooks/health-check-failing"

      - alert: DatabaseConnectionIssues
        expr: 'rate({service="slam-poker"} |= "Failed to" | json | error != "" [5m]) > 0.01'
        for: 2m
        labels:
          severity: warning
          category: database
          service: slam-poker
        annotations:
          summary: "Potential database connection issues"
          description: "High rate of 'Failed to' errors suggesting connectivity problems"
          runbook_url: "https://docs.example.com/runbooks/database-issues"

  - name: slam-poker-business-critical
    interval: 300s
    rules:
      - alert: ZeroActiveUsers
        expr: '{service="slam-poker"} |= "total_active_users" | json | total_active_users != "" | unwrap total_active_users == 0'
        for: 10m
        labels:
          severity: warning
          category: business-critical
          service: slam-poker
        annotations:
          summary: "No active users for extended period"
          description: "Zero active users detected for 10+ minutes during business hours"
          runbook_url: "https://docs.example.com/runbooks/no-active-users"

      - alert: NoRoomCreations
        expr: 'absent_over_time({service="slam-poker"} |= "Room created" [30m])'
        for: 15m
        labels:
          severity: warning
          category: business-critical
          service: slam-poker
        annotations:
          summary: "No room creations detected"
          description: "No room creation activity in the last 30 minutes"
          runbook_url: "https://docs.example.com/runbooks/no-room-creations"

      - alert: FeatureDegradation
        expr: '{service="slam-poker"} |= "voting_completion_rate" | json | voting_completion_rate != "" | unwrap voting_completion_rate < 50'
        for: 20m
        labels:
          severity: critical
          category: business-critical
          service: slam-poker
        annotations:
          summary: "Core feature severely degraded"
          description: "Voting completion rate is {{ $value }}%, indicating severe feature degradation"
          runbook_url: "https://docs.example.com/runbooks/feature-degradation"
