apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    # URL should match the LOKI_URL from your .env file
    # Default: http://192.168.1.100:3100 (update as needed)
    url: ${LOKI_URL:http://192.168.1.100:3100}
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      # Loki-specific configuration
      maxLines: 1000
      # Enable derived fields for better log navigation
      derivedFields:
        - name: "Correlation ID"
          matcherRegex: '"correlation_id":"([^"]+)"'
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{service=\\\"slam-poker\\\"} |= \\\"$${__value.raw}\\\"\"}]"
        - name: "User ID"
          matcherRegex: '"userId":"([^"]+)"'
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{service=\\\"slam-poker\\\"} |= \\\"userId\\\":\\\"$${__value.raw}\\\"\"}]"
        - name: "Room Code"
          matcherRegex: '"roomCode":"([^"]+)"'
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{service=\\\"slam-poker\\\"} |= \\\"roomCode\\\":\\\"$${__value.raw}\\\"\"}]"
        - name: "Socket ID"
          matcherRegex: '"socketId":"([^"]+)"'
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{service=\\\"slam-poker\\\"} |= \\\"socketId\\\":\\\"$${__value.raw}\\\"\"}]"
        - name: "Error Category"
          matcherRegex: '"error_category":"([^"]+)"'
          url: "/explore?orgId=1&left=[\"now-1h\",\"now\",\"Loki\",{\"expr\":\"{service=\\\"slam-poker\\\"} |= \\\"error_category\\\":\\\"$${__value.raw}\\\"\"}]"
      # Alert manager configuration (if using)
      alertmanagerUid: ""
